services:

  # --------------------------------------------------------------------------------------------------------------------
  # APLIKACJA WEBOWA ORDER-WEBAPP
  # --------------------------------------------------------------------------------------------------------------------
  orders-webapp:
    restart: always
    build:
      context: ./order_app
      dockerfile: Dockerfile
    volumes:
      - ./order_app:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - order-app-network

  # --------------------------------------------------------------------------------------------------------------------
  # MYSQL
  # --------------------------------------------------------------------------------------------------------------------
  mysql: #host
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      TZ: Europe/Warsaw
    ports:
      - "3308:3308"
    expose:
      - 3308
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - order-app-network

  mysql-test:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_orders_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3310:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    networks:
      - order-app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 5s
      retries: 10


networks:
  order-app-network:

volumes:
  mysql:
  mysql-test-data:

# ----------------------------------------------------------------------------------------------------------------------
# Instalacja dependencies
# >> poetry install --with dev

# ----------------------------------------------------------------------------------------------------------------------
# Uruchom kontenery:
# >> docker-compose up -d --build

# ----------------------------------------------------------------------------------------------------------------------
# Podejrzyj logi:
# >> docker-compose logs -f

# ----------------------------------------------------------------------------------------------------------------------
# Tworzenie / wdrazanie migracji

# Inicjalizacja migrations:
# >> docker exec -it [container id] bash
# >> flask db init

# Tworzenie pierwszej migracji
# >> docker-compose exec orders-webapp flask db migrate -m "Store schema created"
# >> docker-compose exec orders-webapp flask db upgrade

# ----------------------------------------------------------------------------------------------------------------------
# Ladowanie danych poczatkowych (nie musisz tego robic, ale chce pokazac, jak to zrobic)
# >> docker-compose cp db/seed/seed.sql mysql:/seed.sql
# >> docker-compose exec mysql sh -lc 'mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" < /seed.sql'

# ----------------------------------------------------------------------------------------------------------------------
# Testowanie
# >> poetry run pytest --cov=webapp --cov-report=html